# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */


user_pref("intl.accept_languages", "pt-BR, pt, en-US, en");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.http.phishy-userpass-length", 255);
user_pref("app.update.enabled", false);
user_pref("browser.search.update", false);
user_pref("extensions.update.enabled", false);